#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

echo "==> Installing ri documentation"
gem rdoc --all --ri --no-rdoc

if ! gem spec bundler > /dev/null 2>&1; then
	echo "==> Bundler installation was not detected, installing now via Rubygems"
	gem install bundler -v "=1.12.5"
fi

script/bundle

echo "==> DocumentationBot is ready to go!"