#!/bin/sh

# script/start: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

if [ -f "slack_api_token" ] && [ -z "$SLACK_API_TOKEN" ]; then
	SLACK_API_TOKEN=`cat slack_api_token`
fi

if [ -z "$SLACK_API_TOKEN" ]; then
	echo "ERROR: SLACK_API_TOKEN environment variable must be set before the bot can be started."
	exit 1
fi

echo "RUNNING PROGRAM BLEEP BLORP"

 # /\ /\ /\  THAT IS HOW TO SET ENV VARIABLES and HERE IS WHERE I SHOULD PUT THE SCRIPT TO RUN THE AUTH VARIABLE

# boot the app and any other necessary processes.
#foreman start -p 9393