#!/bin/sh

# script/start: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# Make sure the Slack API token has been set
if [ -f "config/slack_api_token" ] && [ -z "$SLACK_API_TOKEN" ]; then
	SLACK_API_TOKEN=`cat config/slack_api_token`
fi

if [ -z "$SLACK_API_TOKEN" ]; then
	echo "ERROR: SLACK_API_TOKEN environment variable must be set before the bot can be started."
	exit 1
fi

# Start the app running
SLACK_API_TOKEN=$SLACK_API_TOKEN bundle exec ruby start.rb
